### ISSUE TITLE
Feature Request: Pretty Print

### ISSUE THREAD

**Issue by deldrid1** [electricimp/JSONEncoder#1]
Low on my list of my priorities (which is why I'm raising the issue instead of a pull request) but certainly useful for debugging would be the option of pretty printing the output instead of dumping the "uglified" and fully escaped string.

**Comment by myurasov** [comment]
Agree, totally useful feature.

**Comment by betzrhodes** [comment]
A pretty print library has been released.  https://github.com/electricimp/PrettyPrinter
