### ISSUE TITLE
Empty blobs cause error

### ISSUE THREAD

**Issue by jayeheffernan** [electricimp/JSONEncoder#5]
Trying to JSON encode an empty blob will throw an error.

This is due to some very odd and undocumented behaviour in `Blob.tostring()`: calling `.tostring()` on an empty blob will return `null` (not a string!).  To me this looks like a bug in the implementation of `Blob.tostring()`, but in the meantime JSONEncoder should try to work around it.

**Comment by ppetrosh** [comment]
@jayeheffernan, thanks for catching this issue! Looks like a bug to me. And this is something that should probably be fixed on the impOS side. We'll look into this.

**Comment by ppetrosh** [comment]
The fix is going to be published in impOS release 36. Meanwhile I propose the following workaround https://github.com/electricimp/JSONEncoder/pull/6.
